### ISSUE TITLE
Unable to activate plugin

### ISSUE THREAD

**Issue by TacTicTow** [leszcz/mybb-servers-board#1]
From the website and your version, neither will activate. I keep getting the following errors. 

`Fatal error: Uncaught mysqli_sql_exception: BLOB, TEXT, GEOMETRY or JSON column 'cache' can't have a default value in /usr/www/sb/public/mybb/inc/db_mysqli.php:335 Stack trace: #0 /usr/www/sb/public/mybb/inc/db_mysqli.php(335): mysqli_query() #1 /usr/www/sb/public/mybb/inc/db_mysqli.php(378): DB_MySQLi->query() #2 /usr/www/sb/public/mybb/inc/plugins/serversboard.php(108): DB_MySQLi->write_query() #3 /usr/www/sb/public/mybb/admin/modules/config/plugins.php(432): serversboard_install() #4 /usr/www/sb/public/mybb/admin/index.php(830): require('...') #5 {main} thrown in /usr/www/sb/public/mybb/inc/db_mysqli.php on line 335`

Using your latest version from git and MyBB 1.8.37

**Comment by leszcz** [comment]
Hi, thanks for information. 
I want change it in this week.
